#!/bin/bash
# Iterate through all files whose name begins with example_file.
for file in example_file*; do
# Check if the current file is exactly example_file1.
 if [[ "${file}" == "example_file1" ]]; then
 # It displays a message indicating that the file will be skipped.
 echo "Skipping the first file"
 # Skip to the next iteration of the loop, avoiding executing what follows for that file.
 continue
 fi
 # Write a random number generated by $RANDOM into the current file (overwriting its contents).
 echo "${RANDOM}" > "${file}"
 # End the loop.
done